export enum AddressRegion {
  CHERKASY_REGION = 'CHERKASY_REGION',
  CHERNIHIV_REGION = 'CHERNIHIV_REGION',
  CHERNIVTSI_REGION = 'CHERNIVTSI_REGION',
  COUNTRY_WIDE = 'COUNTRY_WIDE',
  UNKNOWN = 'UNKNOWN',
}

export enum AddressCountrySide {
  CENTER = 'CENTER',
  EAST = 'EAST',
  SOUTH = 'SOUTH',
  WEST = 'WEST',
  UNKNOWN = 'UNKNOWN',
}
